# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

step_stone <- function(x, times) {
    .Call('_stoneskip_step_stone', PACKAGE = 'stoneskip', x, times)
}

